// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HighlightElementToggle: typeof import('./src/components/HighlightElementToggle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    StatsTable: typeof import('./src/components/StatsTable.vue')['default']
    SudokuBoard: typeof import('./src/components/SudokuBoard.vue')['default']
    SudokuGrid: typeof import('./src/components/SudokuGrid.vue')['default']
    SudokuHint: typeof import('./src/components/SudokuHint.vue')['default']
  }
}
